language: node_js

node_js:
    - "7"
    - "8"
    - "10"
    - "12"

sudo: false

script:
    - yarn lint
    - yarn test
    - yarn coverage

after_success:
    - yarn coveralls
    - yarn codeclimate

notifications:
    email:
        tom.kaczocha.code@gmail.com
